# Generated by Django 6.1.1 on 2026-09-16 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boutiques/images/')),
                ('couleur_principale', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('SUSPENDUE', 'Suspendue')], default='BROUILLON', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
