# Generated by Django 6.1.1 on 2026-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_latitude_boutique_longitude'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='moyens_paiement',
            field=models.ManyToManyField(blank=True, related_name='boutiques', to='produits.moyenpaiement'),
        ),
    ]
