# Generated by Django 6.1.1 on 2026-09-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0003_boutique_moyens_paiement'),
        ('categories', '0002_moyenpaiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boutique',
            name='moyens_paiement',
        ),
        migrations.AddField(
            model_name='boutique',
            name='moyens_paiement',
            field=models.ManyToManyField(blank=True, related_name='boutiques', to='categories.moyenpaiement'),
        ),
    ]
