# Generated by Django 6.1.1 on 2026-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0004_remove_boutique_moyens_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='boutique',
            name='palette',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='boutique',
            name='photo_agronome',
            field=models.ImageField(blank=True, null=True, upload_to='boutiques/agronomes/'),
        ),
        migrations.AddField(
            model_name='boutique',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
    ]
