# Generated by Django 6.1.1 on 2026-09-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('livraisons', '0003_configurationlivraisonboutique_frais_livraison_fixe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='mode_livraison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='livraisons.modelivraison'),
        ),
    ]
