# Generated by Django 6.1.1 on 2026-09-21 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnements', '0002_alter_abonnement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('ABONNEMENT', 'Abonnement'), ('COMMANDE', 'Commande')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_paiement', models.CharField(blank=True, choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('FREE_MONEY', 'Free Money'), ('EXPRESSO', 'Expresso'), ('CARTE', 'Carte bancaire')], max_length=30, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ECHEC', 'Échec'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('reference', models.CharField(max_length=150, unique=True)),
                ('token_paydunya', models.CharField(blank=True, max_length=255, null=True)),
                ('url_paiement', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='abonnements.abonnementagronome')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
    ]
