# Generated by Django 6.1.1 on 2026-09-26 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_mode_livraison'),
        ('paiements', '0001_initial'),
        ('produits', '0002_remove_produit_stock_produit_stock_actuel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='commandes',
            field=models.ManyToManyField(blank=True, related_name='paiements', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='produits.moyenpaiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to=settings.AUTH_USER_MODEL),
        ),
    ]
