# Generated by Django 6.1.1 on 2026-09-27 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_commande_mode_livraison'),
        ('paiements', '0002_paiement_commandes_alter_paiement_moyen_paiement_and_more'),
        ('utilisateurs', '0005_comptereversement_delete_comptepaydunya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reversement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('VERSE', 'Versé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agronome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversements', to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversement', to='commandes.commande')),
                ('compte_reversement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversements', to='utilisateurs.comptereversement')),
            ],
        ),
    ]
