# Generated by Django 6.1.1 on 2026-09-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_moyenpaiement'),
        ('paiements', '0003_reversement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='categories.moyenpaiement'),
        ),
    ]
