# Generated by Django 6.1.1 on 2026-09-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_email_verifie_verificationemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptePayDunya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_alias', models.CharField(max_length=255, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_paydunya', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
