# Generated by Django 6.1.1 on 2026-09-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_comptepaydunya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptepaydunya',
            name='account_alias',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
