# Generated by Django 6.1.1 on 2026-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('OPPORTUNITE', 'Opportunité'), ('ACTUALITE', 'Actualité'), ('EVENEMENT', 'Événement'), ('FORMATION', 'Formation')], max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date_publication', models.DateTimeField()),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Information agricole',
                'verbose_name_plural': 'Informations agricoles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
