# Generated by Django 6.1.1 on 2026-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_alter_informationagricole_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationagricole',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
