# Generated by Django 6.1.1 on 2026-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_annuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnement',
                'ordering': ['-date_modification'],
            },
        ),
    ]
