# Generated by Django 6.1.1 on 2026-09-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'verbose_name': 'Configuration abonnement', 'verbose_name_plural': 'Configuration abonnement'},
        ),
        migrations.AddField(
            model_name='abonnement',
            name='duree_essai_jours',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='essai_gratuit_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AbonnementAgronome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('ESSAI', 'Essai gratuit'), ('MENSUEL', 'Abonnement mensuel'), ('ANNUEL', 'Abonnement annuel')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('NON_REQUIS', 'Non requis'), ('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('ECHEC', 'Échec')], default='NON_REQUIS', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agronome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement agronome',
                'verbose_name_plural': 'Abonnements agronomes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
