# Generated by Django 6.1.1 on 2026-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Créneau de livraison',
                'verbose_name_plural': 'Créneaux de livraison',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ModeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mode de livraison',
                'verbose_name_plural': 'Modes de livraison',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametreLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regroupement_automatique', models.BooleanField(default=True)),
                ('nombre_max_commandes', models.PositiveIntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de livraison',
                'verbose_name_plural': 'Paramètres de livraison',
            },
        ),
    ]
