# Generated by Django 6.1.1 on 2026-09-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiques', '0002_boutique_latitude_boutique_longitude'),
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationLivraisonBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livraison_par_acheteur', models.BooleanField(default=False)),
                ('livraison_par_agronome', models.BooleanField(default=False)),
                ('nombre_max_commandes_par_livreur', models.PositiveIntegerField(default=5)),
                ('regroupement_automatique', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('boutique', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_livraison', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Configuration de livraison',
                'verbose_name_plural': 'Configurations de livraison',
            },
        ),
        migrations.CreateModel(
            name='ContactLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_livreurs', to='boutiques.boutique')),
            ],
            options={
                'verbose_name': 'Contact livreur',
                'verbose_name_plural': 'Contacts livreurs',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='CreneauLivraison',
        ),
        migrations.RemoveField(
            model_name='parametrelivraison',
            name='nombre_max_commandes',
        ),
    ]
