# Generated by Django 6.1.1 on 2026-09-26 00:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_configurationlivraisonboutique_contactlivreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationlivraisonboutique',
            name='frais_livraison_fixe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='configurationlivraisonboutique',
            name='type_tarification',
            field=models.CharField(choices=[('FIXE', 'Tarif fixe'), ('DISTANCE', 'Tarif selon la distance')], default='FIXE', max_length=20),
        ),
        migrations.CreateModel(
            name='TarifLivraisonDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_min_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distance_max_km', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_distance', to='livraisons.configurationlivraisonboutique')),
            ],
            options={
                'ordering': ['distance_min_km'],
            },
        ),
    ]
