# Generated by Django 6.1.1 on 2026-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0003_configurationlivraisonboutique_frais_livraison_fixe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationlivraisonboutique',
            name='livraison_par_acheteur',
        ),
        migrations.RemoveField(
            model_name='configurationlivraisonboutique',
            name='livraison_par_agronome',
        ),
        migrations.AddField(
            model_name='configurationlivraisonboutique',
            name='modes_livraison',
            field=models.ManyToManyField(blank=True, related_name='configurations_boutiques', to='livraisons.modelivraison'),
        ),
    ]
