# Generated by Django 6.1.1 on 2026-09-30 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_moyenpaiement'),
        ('paiements', '0004_alter_paiement_moyen_paiement'),
        ('produits', '0002_remove_produit_stock_produit_stock_actuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='categories.categorie'),
        ),
        migrations.DeleteModel(
            name='MoyenPaiement',
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='categories.unitevente'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='UniteVente',
        ),
    ]
