# Generated by Django 6.1.1 on 2026-09-30 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_categorie_delete_moyenpaiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_vendue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
